packageName: vectorizer_ai
projectName: vectorizer-ai-sdk
packageVersion: 1.0.0
packageUrl: https://github.com/clv/vectorizer-ai-python
gitUserId: clv
gitRepoId: vectorizer-ai-python
hideGenerationTimestamp: true
